export default () => <>
  <h2>simplified japanese</h2>

  <h3>名詞</h3>
  <div className='tables'>
    <table>
      <tr>
        <th>主</th>
        <th>對</th>
        <th>與</th>
        <th>屬</th>
      </tr>
      <tr>
        <td>∅</td>
        <td>vo</td>
        <td>pe</td>
        <td>no</td>
      </tr>
    </table>
  </div>

  <h3>動詞</h3>
  子音や母音が連續せぬ樣に接續す.
  <div className='tables'>
    <table>
      <tr>
        <th></th>
        <th></th>
        <th>子</th>
        <th>母</th>
      </tr>
      <tr>
        <th>詞幹</th>
        <td></td>
        <td>kak-</td>
        <td>mi-</td>
      </tr>
      <tr>
        <th>終止</th>
        <td>-(l)</td>
        <td>kak-∅</td>
        <td>mi-l</td>
      </tr>
      <tr>
        <th>使役</th>
        <td>-(s)as</td>
        <td>kak-as</td>
        <td>mi-sas</td>
      </tr>
      <tr>
        <th>可能</th>
        <td>-(l)aj</td>
        <td>kak-aj</td>
        <td>mi-laj</td>
      </tr>
      <tr>
        <th>必然</th>
        <td>-(u)bekal</td>
        <td>kak-ubekal</td>
        <td>mi-bekal</td>
      </tr>
      <tr>
        <th>意志</th>
        <td>-(a)m</td>
        <td>kak-am</td>
        <td>mi-m</td>
      </tr>
      <tr>
        <th>完了</th>
        <td>-(i)n</td>
        <td>kak-in</td>
        <td>mi-n</td>
      </tr>
      <tr>
        <th>假定</th>
        <td>-(a)ba</td>
        <td>kak-aba</td>
        <td>mi-ba</td>
      </tr>
      <tr>
        <th>理由</th>
        <td>-(l)eba</td>
        <td>kak-eba</td>
        <td>mi-leba</td>
      </tr>
      <tr>
        <th>命令</th>
        <td>-(e)jo</td>
        <td>kak-ejo</td>
        <td>mi-jo</td>
      </tr>
      <tr>
        <th>抽象</th>
        <td>-(l)aku</td>
        <td>kak-aku</td>
        <td>mi-laku</td>
      </tr>
    </table>
  </div>

  <h3>漢字</h3>
</>
